name: arm64

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.c"
      - ".github/workflows/arm64.yml"
  pull_request:

jobs:
  aarch64:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Ubuntu arm64

    steps:
      - uses: actions/checkout@v2

      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          install: |
            apt-get update -q -y
            apt-get install -q -y cmake gcc

          run: |
            echo "Minimal"
            uname -m
            apt-get update -y 
            df -h
            DEBIAN_FRONTEND="noninteractive" TZ="Europe/London" apt-get install -y python curl build-essential unzip git
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            git clone --recurse-submodules https://github.com/denoland/deno.git /deno
            export PATH="/root/.cargo/bin:${PATH}"
            cd /deno/
            rustup target add wasm32-unknown-unknown
            rustup target add wasm32-wasi
            cargo build --release --locked 
