name: arm64
on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.c"
      - ".github/workflows/arm64.yml"
  pull_request:
jobs:
  aarch64:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Ubuntu arm64

    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04
          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -q -y curl gcc maven
            curl -OL https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/23.0.0-dev-20221215_2038/graalvm-ce-java17-linux-aarch64-dev.tar.gz
            tar -xzvf graalvm-ce-java17-linux-aarch64-dev.tar.gz
            export JAVA_HOME=$(pwd)/graalvm-ce-java17-linux-aarch64-dev/
            export PATH=$JAVA_HOME/bin:$PATH
            gu install native-image
          run: |
            git clone https://github.com/apache/maven-mvnd.git
            cd maven-mvnd
            mvn clean verify -Pnative
            file client/target/mvnd
